[package]
name = "grieg-cli"
version = "0.2.0"
edition = "2021"

[dependencies]
serde        = { workspace = true }
serde_json   = { workspace = true }
grieg-engine = { path = "../grieg-engine" }
grieg-parser = { path = "../grieg-parser" }

[features]
emit_geometry = []