name: python-wheel
on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:
jobs:
  build-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip maturin
      - working-directory: grieg-py
        run: maturin build --release
      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: grieg-py/target/wheels/*.whl
